---
- name: generate admin keyring from provided secret (external cluster)
  command: ceph-authtool /etc/ceph/{{ cluster }}.client.admin.keyring --create-keyring --name=client.admin --add-key={{ client_node_external_cluster }} --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow'
  args:
    creates: /etc/ceph/{{ cluster }}.client.admin.keyring
  when:
    - client_node_external_cluster != false
    - cephx

- name: fetch the generated admin keyring (external cluster)
  fetch:
    src: /etc/ceph/{{ cluster }}.client.admin.keyring
    dest: "{{ fetch_directory }}/{{ fsid }}/{{ cluster }}.client.admin.keyring"
    flat: yes
  when:
    - cephx
    - client_node_external_cluster != false

- name: copy ceph admin keyring
  copy:
    src: "{{ fetch_directory }}/{{ fsid }}/etc/ceph/{{ cluster }}.client.admin.keyring"
    dest: "/etc/ceph/"
    owner: "ceph"
    group: "ceph"
    mode: "0600"
  when:
    - cephx
    - not client_node_external_cluster

- name: check if global key exists in ceph_conf_overrides
  set_fact:
    global_in_ceph_conf_overrides: "{{ 'global' in ceph_conf_overrides }}"
