---
- name: use ceph-volume to create filestore osds with dedicated journals
  command: "ceph-volume lvm create --filestore --data {{ item.key }} --journal {{ item.value }}"
  with_dict: "{{ lvm_volumes }}"
